# Generated by Django 2.1.3 on 2019-02-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='image',
            field=models.ImageField(default='default.png', upload_to='Images/'),
        ),
    ]
