# Generated by Django 2.1.3 on 2019-02-05 02:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
