# Generated by Django 2.1.3 on 2019-02-07 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stars',
            new_name='Star',
        ),
    ]
