# Generated by Django 2.1.3 on 2019-02-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stars', '0002_auto_20190207_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='star',
            name='image',
            field=models.ImageField(default='default.png', upload_to='Images/'),
        ),
    ]
